### ISSUE TITLE
Raise push request againt core jenkins job builder repo

### ISSUE THREAD

**Issue by rozky** [asmundg/jenkins-jobs-slack#3]
Hi,

please, could you push this to the main repo https://github.com/openstack-infra/jenkins-job-builder?

Thanks,
Michal

**Comment by asmundg** [comment]
Hi.

I wasn't planning on doing that, but feel free to submit a pull request to the openstack-infra repo if you want this included in the core.

**Comment by filler** [comment]
@rozky, I believe there are multiple patchset proposals to land this in jjb core:

https://review.openstack.org/#/c/131404/
https://review.openstack.org/#/c/136627/

@asmundg, thanks for this plugin.  :100: :star2:

**Comment by yveshwang** [comment]
+1

**Comment by mrozlukasz** [comment]
+1

**Comment by asmundg** [comment]
It looks like slack support is included in jjb core now: https://github.com/openstack-infra/jenkins-job-builder/commit/7e02657f857fef7e6fc21faa2c040c5e1dc5b56c
