### ISSUE TITLE
Use secret ID instead of inline the auth-token itself

### ISSUE THREAD

**Issue by ayashjorden** [asmundg/jenkins-jobs-slack#9]
Hello,
Using this publisher was pretty straight forward 👍 

Is there a way to use a Jenkins' credential ID instead of inline the auth-token itself?

Best,
Yarden

**Comment by asmundg** [comment]
Hi. It has been quite a while since I used Jenkins. So I'm afraid I won't do anything about this in the immediate future. Anyone's welcome to help, though. :)

**Comment by trcox** [comment]
@ayashjorden If you are still searching for this it was added in jenkins-job-builder v2.0 [here](https://github.com/openstack-infra/jenkins-job-builder/commit/69755a0b8d1107382d74442198387bec84ef8b9e#diff-ff0ea50812cc2ac14f57fa50a05066fc).

**Comment by ayashjorden** [comment]
Thank you @trcox , I'll have a look 👍
